version: "3"

services:

 snipeit1:
    container_name: snipeit1
    restart: always
    image: snipe/snipe-it:latest
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_KEY: "base64:<<APPKEY_HERE>>>"
      APP_URL: "http://YOUR.IP.ADD.HERE:PORT"
      APP_TIMEZONE: "Europe/Berlin"
      APP_LOCALE: "de"
      MYSQL_ROOT_PASSWORD: "psssssstveryerysecret"
      MYSQL_DATABASE: "snipeit"
      MYSQL_USER: "snipeit"
      MYSQL_PASSWORD: "psssssstveryerysecret"
      MYSQL_PORT_3306_TCP_ADDR: "mysql"
    links:
      - snipeit_db1:mysql
    ports:
      - 80:80
      - 443:443

 snipeit_db1:
    container_name: snipeit_db1
    restart: always
    image: mysql:5.6
    environment:
       MYSQL_ROOT_PASSWORD: "psssssstveryerysecret"
       MYSQL_DATABASE: "snipeit"
       MYSQL_USER: "snipeit"
       MYSQL_PASSWORD: "psssssstveryerysecret"
    ports:
      - 3306:3306
